/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Administrator
 */

public class AplikasiPenampilGambar extends javax.swing.JFrame {
   
    /**
     * Creates new form AplikasiPenampilGambar
     */
    public AplikasiPenampilGambar() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        cbbx = new javax.swing.JComboBox<>();
        btnrainbow = new javax.swing.JButton();
        btngedung = new javax.swing.JButton();
        btnblue = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        gedung = new javax.swing.JLabel();
        rainbow = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        buttonpanel.setMaximumSize(new java.awt.Dimension(300, 400));
        buttonpanel.setMinimumSize(new java.awt.Dimension(300, 400));
        buttonpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 100, 100));

        cbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rainbow", "Gedung", "Blue" }));
        cbbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbxItemStateChanged(evt);
            }
        });
        buttonpanel.add(cbbx);

        btnrainbow.setText("raimbow");
        btnrainbow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrainbowActionPerformed(evt);
            }
        });
        buttonpanel.add(btnrainbow);

        btngedung.setText("gedung");
        btngedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngedungActionPerformed(evt);
            }
        });
        buttonpanel.add(btngedung);

        btnblue.setText("blue");
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });
        buttonpanel.add(btnblue);

        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        buttonpanel.add(btnexit);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        imagepanel.setLayout(new java.awt.CardLayout());

        gedung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bgg2.jpg"))); // NOI18N
        gedung.setMaximumSize(new java.awt.Dimension(316, 400));
        gedung.setMinimumSize(new java.awt.Dimension(316, 400));
        gedung.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(gedung, "1");

        rainbow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bgg1.jpg"))); // NOI18N
        rainbow.setMaximumSize(new java.awt.Dimension(316, 400));
        rainbow.setMinimumSize(new java.awt.Dimension(316, 400));
        rainbow.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(rainbow, "0");
        rainbow.getAccessibleContext().setAccessibleName("0");

        blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bgg3.jpg"))); // NOI18N
        blue.setMaximumSize(new java.awt.Dimension(316, 400));
        blue.setMinimumSize(new java.awt.Dimension(316, 400));
        blue.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(blue, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrainbowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrainbowActionPerformed
    CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "0");
    }//GEN-LAST:event_btnrainbowActionPerformed

    private void btngedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngedungActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "1");
    }//GEN-LAST:event_btngedungActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
         CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "2");
    }//GEN-LAST:event_btnblueActionPerformed

    private void cbbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbxItemStateChanged
      CardLayout cl= (CardLayout)(imagepanel.getLayout());
      cl.show(imagepanel, String.valueOf(cbbx.getSelectedIndex()));
    }//GEN-LAST:event_cbbxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable(){
     public void run(){
     AplikasiPenampilGambar fullframe = new AplikasiPenampilGambar();
         GraphicsDevice device=
                 GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
         device.setFullScreenWindow(fullframe);
         fullframe.setVisible(true);
     }
    });
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blue;
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngedung;
    private javax.swing.JButton btnrainbow;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JComboBox<String> cbbx;
    private javax.swing.JLabel gedung;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JLabel rainbow;
    // End of variables declaration//GEN-END:variables
}
